spring.application.name=saga-wallet-system

# 1. CHANGE THIS TO 'none'
# We will create the tables manually to ensure they are identical on all shards.
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 2. ADD THESE NAMING STRATEGIES
# This ensures Hibernate uses the EXACT name you put in @Table(name="...")
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

spring.datasource.url=jdbc:shardingsphere:classpath:sharding.yml
spring.datasource.driver-class-name=org.apache.shardingsphere.driver.ShardingSphereDriver
spring.shardingsphere.props.sql-show=true